name: Deploy Inventory-Uploader-Frontend-Docker from Github to AWS EB
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@v2

      #   - name: Install Node.js
      #     uses: actions/setup-node@v2
      #     with:
      #       node-version: {{ matrix.node-version }}

      #   - name: Install dependencies
      #     run: npm install

      #   - name: Build React App
      #     run: npm run build

      - name: Generate Deployment Package
        run: zip -r app.zip * -x "**.git**"

      - name: Get timestamp
        id: current-time
        run: echo "::set-output name=replaced::$(date +'%Y%m%d%H%M%S')"

      - name: Run string replace
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: "${{ secrets.ACCESS_KEY }}"
          aws_secret_key: "${{ secrets.SECRET_ACCESS_KEY }}"
          application_name: Inventory-Uploader-Frontend-Docker
          environment_name: Inventory-Uploader-Frontend-Docker-dev
          version_label: "app-${{ steps.current-time.outputs.replaced }}"
          region: us-east-1
          deployment_package: app.zip

      - name: Deployed!
        run: frontend App deployed to ELB
